spring:
  application:
    name: author-book-rest
  datasource:
    url: jdbc:mysql://localhost:3306/author_book?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  liquibase:
    change-log: classpath:/db/changelog.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaitspace@gmail.com
    password: ylfj tpdn xwmw qltd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

server:
  port: 8080